### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by index49** [HDF-NI/hdf5.node#117]
attempt to yarn install hdf5 results in

In file included from ../src/uint64.cc:1:
../src/uint64.hpp:24:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> target);

**Comment by rimmartin** [comment]
Hi, which version of node?

I'll be looking at version compatibility and upgrading over the holiday break.

**Comment by index49** [comment]
Node v15.0.1


on a MacOS Catalina 10.15.7


Apple clang version 11.0.0 (clang-1100.0.33.17

**Comment by peterforeman** [comment]
Also not working with Docker, library/node:lts (14.6.0) but also with 10. Same errors as @index49 mentions.

It does work with library/node:8, after apt update && apt install libhdf5-dev && npm install hdf5 --hdf5_home_linux=/usr/lib/x86_64-linux-gnu/hdf5/serial
