### PR TITLE
Feature get dataset id

### PR DESCRIPTION
**Pull request by pietervanleeuwen**
Dealing with HDF5 files containing sensor measurements a separate dataset contains the clock signal that keeps track of the exact timings of the measurements. To keep track of this all measurement datasets keep a reference attribute (H5T_REFERENCE) to the clock channel. 

In order to be able to work with these files in hdf5.node I've modified the _getDatasetAttributes_ to return the reference attribute as a string where before this type was ignored. This is similar to the HDF5 java implementation that also returns the string id of the item referenced.

To match the reference id to a dataset I also added the method _getDatasetId_ to retrieve the dataset id. Combined this allows to check what dataset is being referred to in other datasets.

### CODE REVIEW

**Comment by rimmartin** [comment]
Hi, I'll need to study this one more.

Is the 'id' a string  and name?  Will this be confusing to the 64 bit integer id's of groups, datasets etc?

**Comment by pietervanleeuwen** [comment]
The id is the dataset id that is being referenced using an object reference. 

In the following image you can see the Calc_Fx dataset that contains an attribute _bases_ that contains the object reference to the Time dataset (image made using HDFView)

hdf5-object-reference

**Comment by rimmartin** [comment]
I was referring to https://support.hdfgroup.org/HDF5/doc/RM/RM_H5D.html#Dataset-Open returns a dataset id.  Isn't the method name getDatasetId confusing for users?  They might think they are getting the id.

Also running with hdf5 1.10.x? 32 bit can't do it; needs to be 64 bit; that's why the wrapper Int64 was introduced

Also the group's childId is the H5T_REFERENCE is the objinfo.addr?

  I will study more; there are other methods that may be available. Do you have a test h5 file?

**Comment by rimmartin** [comment]
Also Number can't do it because they at 53 bit; from the mantissa of a double

**Comment by rimmartin** [comment]
also as an attribute can't it be the named attribute with value stored in Int64?

**Comment by rimmartin** [comment]
I'm making a reference available on the javascript side which can be constructed as well on the native side to do the reference interface https://support.hdfgroup.org/HDF5/doc1.8/RM/RM_H5R.html.  This will allow for creating and the region functionality as well.

**Comment by pietervanleeuwen** [comment]
The name getDatasetId might indeed be confusing, I was also not aware that the Number only supports 53 bits instead of a 64 bits.

Attached an stripped down example of 1 group containig 4 datasets where three of them are having an object reference using the _bases_ attribute to the time dataset.
[test.h5.zip](https://github.com/HDF-NI/hdf5.node/files/2114207/test.h5.zip)

**Comment by pietervanleeuwen** [comment]
Support for the reference interface, including the creation is indeed a more generic way of reading and adding references to HDF5

**Comment by rimmartin** [comment]
thank you for the example!  This will be a great addition; interesting usage with clock signals.  We'll see what the day brings

**Comment by rimmartin** [comment]
Hi @pietervanleeuwen 

we now have a reference as an attribute attached on the javascript side

```
           var file = new hdf5Lib.hdf5.File('/home/roger/Downloads/test.h5', globs.Access.ACC_RDONLY);
            const group   = file.openGroup('Group_1');
            const readBuffer=h5lt.readDataset(group.id, 'Dataset_1', function(options){
                options.rank.should.equal(2);
                options.rows.should.equal(10);
                options.columns.should.equal(1);
            });
            readBuffer.constructor.name.should.match('Float64Array');
            readBuffer.length.should.match(10);
            var refName=readBuffer.bases.getName(file.id, H5RType.H5R_OBJECT);
            console.log(refName);
            
            group.close();

```
where bases is representing the same attribute as on the h5 dataset.

The output from the above is:
```
/Group_1/Dataset_Time
```
from opening your test.h5. Should work using getDatasetAttributes too(adding a unit test).

The reference can be instantiated on either side.   The getName appears to work.  Now for the rest of H5R https://support.hdfgroup.org/HDF5/doc1.8/RM/RM_H5R.html functionality and getting the time signal you are after.  I believe this will work even if the ref was in another h5 file as well. 

I'll go further and commit in the morning when I'm near a windows and mac box. This is going to be a nice addition:-)

**Comment by rimmartin** [comment]
I'm thinking to send the reference thru the dataset interface

```
const refBuffer=h5lt.readDataset(readBuffer.bases, function(options){
            });
```
to retrieve it; that way it reuses all dataset interface and can internally do the dereference and memory handling.  Thinking about it...

How do you know which entry in the clock signal you want?

**Comment by rimmartin** [comment]
Hi @NINI1988, good to see you.

Not understanding.  The readDataset is still returning a native buffer.  The native buffer just continues to have properties/attributes on it that are the attributes from the h5's dataset.  They also can be gotten with  the group.getDatasetAttributes  method.   It may be good to make the attributes coming back be optional if someone wants to not get dataset attribuites automaticaslly but only by  group.getDatasetAttributes

**Comment by rimmartin** [comment]
The options thing is about the rank, rows etc that are not attributes

**Comment by NINI1988** [comment]
I thought we want to go away from mixing the buffer with other fields?

**Comment by pietervanleeuwen** [comment]
@rimmartin great to see you already started on implementing this!

To answer your question about how we know what entries to get from the time dataset. From the interface we request a range of time we want to plot a graph from a certain data dataset ([example image](https://www.noterik.nl/wp-content/uploads/2018/02/insync_stageplayer_synchronised_playout_measurement_dataV3.jpg) from our application). Then the application calculates the range we need to get from the time dataset and the data dataset and return the two combined as the {x,y} values to plot the graph.

Directly being able to use the _bases_ reference to read the time dataset as you propose with the _referencedBuffer_ would even make this easier to do.

**Comment by rimmartin** [comment]
Hi @pietervanleeuwen, 

this already works using the name
```
            const readBuffer=h5lt.readDataset(group.id, 'Dataset_1', function(options){
                options.rank.should.equal(2);
                options.rows.should.equal(10);
                options.columns.should.equal(1);
            });
            readBuffer.constructor.name.should.match('Float64Array');
            readBuffer.length.should.match(10);
            var refName=readBuffer.bases.getName(file.id, H5RType.H5R_OBJECT);
            const refBuffer=h5lt.readDataset(file.id, refName, function(options){
                options.rank.should.equal(2);
                options.rows.should.equal(10);
                options.columns.should.equal(1);
            });

```
When I get to work I'll commit this far

**Comment by rimmartin** [comment]
failed building on windows:

```
c:\nodeprojects\hdf5.node\src\reference.hpp(81): error C2660: 'H5Rdereference' : function does not take 4 arguments (..\src\methods.cc) [c:\NodeProjects\hdf5.node\build\hdf5.vcxproj]
```
This is a hdf5 1.8 vs 1.10 native version issue.  Working on it

**Comment by rimmartin** [comment]
builds on windows and with hdf5 1.8

**Comment by rimmartin** [comment]
for creating reference's I'm thinking to make a second Instantiate function which takes the name of the object and gets the id for it to create the ref

**Comment by rimmartin** [comment]
not working with hdf5 1.8 yet

**Comment by NINI1988** [comment]
I don't want to change things in this project. 

But this doesn't work in typescript:
```
const buffer=new Float64Array(10); buffer.bases=new...
```
Because float64array has no bases property. It only works with casting which I don't like.

**Comment by rimmartin** [comment]
Ah I see, @NINI1988 .  Does the user have to do it for each one?  and they are a bit dynamic.

In the picture in https://github.com/HDF-NI/hdf5.node/pull/94#issuecomment-398091140
there is a General and an Attributes tab.  When I was talking with you before I was meaning separating the 'made up' properties I had done for the general such as rank.  I didn't understand that you were meaning all properties/attributes not on the hierarchy of file, groups and datasets.  Yet that is very much the paradigm from the beginning of this project.  Not a wrapper api but a one-to-one javascript to the hdf5 hierarchy.  Which works so well for javascript.

Is there nothing to make it work in typescript?  I'll study some more typescript.  is there no way to find the child properties readily?

**Comment by rimmartin** [comment]
there are years of discussion at
https://stackoverflow.com/questions/12710905/how-do-i-dynamically-assign-properties-to-an-object-in-typescript
nothing satisfactory?

**Comment by rimmartin** [comment]
I was also thinking of making it optional for people who only want the dataset data and get the attributes bound later with Group.prototype.getDatasetAttributes(name); but this still has properties on the returned object.
```
var attrs = group.getDatasetAttributes('Dataset_1');
attrs.bases
```
Different since attr is not a specific javascript function like FLoat64Array?

The user could do
```
 const readBuffer=h5lt.readDataset(group.id, 'Dataset_1', {skipAttributes: true}, function(options){
                options.rank.should.equal(2);
                options.rows.should.equal(10);
                options.columns.should.equal(1);
            });
var attrs = group.getDatasetAttributes('Dataset_1');

```
would this help?

**Comment by rimmartin** [comment]
And skipAttributes is really only useful for those with rather large attributes.  Typescript can ignore and just call the getDatasetAttributes?

**Comment by NINI1988** [comment]
This would work in typescript with casting
```
Const buffer:hdf5.TypedArray=<hdf5.TypedArray>new float64array();
buffer.bases=...
buffer.attributeName="attributeValue"
```
But this would remove type safety.

What about?
```
const error = h5lt.readDataset(group.id, 'Dataset_1', {}, function(buffer,options, attributes) {});
```
This would work also for async functions.

**Comment by NINI1988** [comment]
What about?
```
const buffer=new float64Array() ;
const attributes={};
attributes.bases=... 
h5lt.makeDataset(group.id, 'Dataset_1', buffer, options, attributes); 
```
This would work in typescript and Javascript.

**Comment by NINI1988** [comment]
And what happens when a user wants to add an attribute with the name "length"? This would overwrites the length function of the float64array. This would be fixed when attributes are separated.

**Comment by rimmartin** [comment]
https://v8docs.nodesource.com/node-8.9/d2/d6f/classv8_1_1_float64_array.html
this(in typescript) happens for all prototype parents of functions? Float64Array is right on top of (v8::)TypedArray.

Maybe the writing/creating of attributes should be more separate for those who want to avoid the name clashes and/or don't want the direct hierarchy. Since there is a  Group.prototype.getDatasetAttributes(name) there could be a setter
```
const attributes={};
attributes.bases=... 
 group.setDatasetAttributes(name, attributes);
```
?
```
and then individual ones:
group.setDatasetAttribute(name, 'bases', new h5lt.Reference(file.id, "/Group_1/Dataset_Time", H5RType.H5R_OBJECT));
```
?

Of course I'm in trouble if they name their attribute 'setDatasetAttributes':-)  Might need a name clash handler. and use underscores. where the hdf5 attribute named 'length' becomes '_length' and if they also have a '_length' it then becomes '__length'; not something I particularly like. 

But have it they can choose not to have the attributes attached directly coming or going

**Comment by NINI1988** [comment]
The seperate function like: 
```
const attributes={};
attributes.bases=... 
group.setDatasetAttributes(name, attributes);

const readAttributes=group.getDatasetAttributes(name);
```
works in typescript.

But i would still prefer not to mix native objects like Float64Array or Buffer with user properties. But this is my opinion.

**Comment by rimmartin** [comment]
I can make it work both ways; you will be able to get/set your api thru functions and others who like the direct binding can get the javascript  hdf5 hierarchy  way.  I'll add this; typescript users won't have the mix

**Comment by NINI1988** [comment]
OK, that sound fine. Thank you for all the work.

**Comment by rimmartin** [comment]
we'll get there
